import = ["/Users/mrsum/.config/alacritty/thm/tokyo-night.toml"]
live_config_reload = true

[font]
size = 16.0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
dynamic_padding = true
opacity = 0.94

[window.padding]
x = 10
y = 20
