import = ["~/.config/alacritty/thm/tokyo-night.toml"]
live_config_reload = true

[env]
  TERM = "alacritty-direct"

[font]
  size = 16.0

[font.normal]
  family = "JetBrainsMonoNL Nerd Font"
  style = "Regular"

[window]
  opacity = 0.98
  decorations = "buttonless"
  dynamic_padding = true

[window.padding]
  x = 10
  y = 20
